# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# PourousPuff2.py
# Created on: 2015-10-05 16:56:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: PourousPuff2 <Thick30m> <Poros3> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
Thick30m = arcpy.GetParameterAsText(0)
if Thick30m == '#' or not Thick30m:
    Thick30m = "C:\\PROJECTS\\MILLVILLE\\Data\\FlowModels.gdb\\Thick30m" # provide a default value if unspecified

Poros3 = arcpy.GetParameterAsText(1)
if Poros3 == '#' or not Poros3:
    Poros3 = "C:\\PROJECTS\\MILLVILLE\\Data\\FlowModels.gdb\\Poros3" # provide a default value if unspecified

# Local variables:
Input_groundwater_head_elevation_raster = ""
Input_formation_transmissivity_raster = ""
Output_direction_raster = ""
Output_magnitude_raster = ""
Value = "50"
FLB_Value_ = "C:\\PROJECTS\\MILLVILLE\\Data\\FlowModels.gdb\\FLB%Value%"
Particl_DarcyVe1_TXT = ""
PPB_Value_ = "C:\\PROJECTS\\MILLVILLE\\Data\\PPB%Value%"

# Process: Darcy Velocity
arcpy.gp.DarcyVelocity_sa(Input_groundwater_head_elevation_raster, Poros3, Thick30m, Input_formation_transmissivity_raster, Output_direction_raster, Output_magnitude_raster)

# Process: For
arcpy.IterateCount_mb("50", "500", "50")

# Process: Particle Track
arcpy.gp.ParticleTrack_sa(Output_direction_raster, Output_magnitude_raster, "431910.55 4615423.59", Particl_DarcyVe1_TXT, "37.9732399999996", Value, FLB_Value_)

# Process: Porous Puff
arcpy.gp.PorousPuff_sa(Particl_DarcyVe1_TXT, Poros3, Thick30m, PPB_Value_, "10000000", "", "", "3", "1", "0")

