# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TRS_MODEL_NO_SDE.py
# Created on: 2014-06-25 13:45:25.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: TRS_MODEL_NO_SDE <infeature> <output> 
# Description: 
# PLSS and CAD
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
infeature = arcpy.GetParameterAsText(0)
if infeature == '#' or not infeature:
    infeature = "infeature" # provide a default value if unspecified

output = arcpy.GetParameterAsText(1)
if output == '#' or not output:
    output = "C:\\Users\\PAULINKENBRANDT\\Documents\\ArcGIS\\Default.gdb\\projj21" # provide a default value if unspecified

# Local variables:
PLSSQQSec = "C:\\GIS\\TRS.gdb\\PLSSQQSec"
PLSSSec = "C:\\GIS\\TRS.gdb\\PLSSSec"
projj = infeature
spajon1 = projj
spajon2 = spajon1
Output_Feature_Class = spajon2
spajon21 = Output_Feature_Class
spajon2__3_ = spajon21
projj21 = spajon2__3_
projj21XY = projj21
projjXYadd = projj21XY
projj2__2_ = projjXYadd
Near_Features = "C:\\GIS\\TRS.gdb\\PLSSQQPoints"

desc =arcpy.Describe(infeature)
refer = desc.SpatialReference

# Process: Project
arcpy.Project_management(infeature, projj, "PROJCS['NAD_1983_UTM_Zone_12N',GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['False_Easting',500000.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',-111.0],PARAMETER['Scale_Factor',0.9996],PARAMETER['Latitude_Of_Origin',0.0],UNIT['Meter',1.0]]", "",refer)

# Process: Spatial Join
arcpy.SpatialJoin_analysis(projj, PLSSSec, spajon1, "JOIN_ONE_TO_ONE", "KEEP_ALL")

# Process: Spatial Join (2)
arcpy.SpatialJoin_analysis(spajon1, PLSSQQSec, spajon2, "JOIN_ONE_TO_ONE", "KEEP_ALL")

# Process: Near
arcpy.Near_analysis(spajon2, Near_Features, "", "NO_LOCATION", "NO_ANGLE", "PLANAR")

# Process: Add Field
arcpy.AddField_management(Output_Feature_Class, "PLSS", "TEXT", "", "", "25", "", "NULLABLE", "NON_REQUIRED", "")

codeblock = '''
def quarterfill(tow, ran, sec, quad, x, a):
    g=x[0:2]
    h=x[2:4]
    m = {'NE':'a','NW':'b','SW':'c','SE':'d'}
    n = {1:'A',2:'B',3:'C',4:'D'}
    qq = m.get(g) or ''
    q = m.get(h) or ''
    j = n.get(quad) or ''
    if a > 90:
        qqq='d'
    elif a <-90:
        qqq='a'
    elif a < 90 and a > 0:
        qqq = 'c'
    elif a < 0 and a > -90:
        qqq = 'b'
    else:
        qqq = ''
    return '('+ str(j)+'-'+ str(int(tow)).rjust(2) + '-' + str(int(ran)).rjust(2)+')'+ str(int(sec)).rjust(2) + q + qq + qqq'''

# Process: Calculate Field
arcpy.CalculateField_management(spajon21, "PLSS", "quarterfill(!TNUM!,!RNUM!,!SNUM!,!QNUM!,!SECDIVNO!,!NEAR_ANGLE!)", "PYTHON_9.3", codeblock)

# Process: Project (2)
arcpy.Project_management(spajon2__3_, projj21, "GEOGCS['GCS_North_American_1983',DATUM['D_North_American_1983',SPHEROID['GRS_1980',6378137.0,298.257222101]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]", "", "")

# Process: Add XY Coordinates
arcpy.AddXY_management(projj21)

# Process: Add Field (2)
arcpy.AddField_management(projj21XY, "USGSCAD", "TEXT", "", "", "20", "", "NULLABLE", "NON_REQUIRED", "")

codeblock = '''
def decdeg(x,y):
  degx = int(abs(x))
  degy = int(abs(y))
  tempx = 60* (abs(x) - degx)
  tempy = 60* (abs(y) - degy)
  minx = int(tempx)
  miny = int(tempy)
  secx = str(int(round(60*(tempx-minx),0))).zfill(2)
  secy = str(int(round(60*(tempy-miny),0))).zfill(2)
  return str(degy).zfill(2)+str(miny).zfill(2)+str(secy).zfill(2)+str(degx).zfill(2)+str(minx).zfill(2)+str(secx).zfill(2)'''


# Process: Calculate Field (2)
arcpy.CalculateField_management(projjXYadd, "USGSCAD", "decdeg(!POINT_X!,!POINT_Y!)", "PYTHON_9.3", codeblock)

# Process: Delete Field
arcpy.DeleteField_management(projj2__2_, "Join_Count;TARGET_FID;SECDIVID;FRSTDIVID_1;SECDIVNO;SECDIVSUF;SECDIVTYP;SECDIVTXT;ACRES;PLSSID_1;SECDIVLAB;SURVTYP_1;SURVTYPTXT_1;Join_Count_1;TARGET_FID_1;FRSTDIVID;TOWNSHIP;RANGE;SECTION;BASEMERIDIAN;FRSTDIVNO;FRSTDIVDUP;FRSTDIVTYP;FRSTDIVTXT;PLSSID;FRSTDIVLAB;SURVTYP;SURVTYPTXT;TNUM;RNUM;SNUM;QNUM;NEAR_FID;NEAR_DIST;NEAR_ANGLE")

